shop/urls.py
from django.urls import path, include
from .views import Home, ItemDetailView, add_to_cart, remove_from_cart, remove_single_item_from_cart, OrderSummaryView,\
    CheckoutView, PaymentView, AboutView, CategoryDetailView, UserSummary

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='list'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('category/<slug>/', CategoryDetailView.as_view(), name='category'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('about/', AboutView.as_view(), name='about'),
    path('user-summary/', UserSummary.as_view(), name='user-summary'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block aside_menu %}{% endblock aside_menu %}

{% block content %}
    <div class="mt-4 my-4">
        <h3>About</h3>
        <p class="font-weight-light text-justify">This is Ecommerce solution created by Mariusz Kosakowski.</p>
        <p class="font-weight-light text-justify">Below is example how can looks text on /about page</p>
        <p class="font-weight-light text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p class="font-weight-light text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p class="font-weight-light text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p class="font-weight-light text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p class="font-weight-light text-justify">Copyright 2020</p>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Ecommerce solution 2020</title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
  {% block extra_head %}{% endblock extra_head %}
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Ecommerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:about' %}">About</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'shop:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% if request.user.is_authenticated %}
              <a href="{% url 'shop:user-summary' %}" class="nav-link">{% if request.user.is_authenticated %} Login as: {{ request.user }}{% endif %}</a>
            {% endif %}
          </li>
          <li>
            {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="nav-link">Logout</a>
            {% else %}
              <a href="{% url 'login' %}" class="nav-link">Login</a>
            {% endif %}
          </li>
          <li>
            {% if not user.is_authenticated %}
              <a href="{% url 'signup' %}" class="nav-link">Signup</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
      <div class="row">
        {% block aside_menu %}
        <div class="col-lg-3">
          <h1 class="my-4">Ecommerce</h1>
          <div class="list-group">
            {% if categories %}
              {% for category in categories %}
                <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category }}</a>
              {% endfor %}
            {% else %}
              <h5>Please add category in admin panel</h5>
            {% endif %}
          </div>
        </div>
        {% endblock aside_menu %}
          <div class="col-lg-9">
            {% block content %}{% endblock content %}
          </div>
      </div>
  </div>
  <!-- /.container -->
  <!-- Footer -->
  {% block footer %}{% endblock footer %}

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_scripts %}
{% endblock extra_scripts %}

</body>

</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
       <h1 class="my-4">Category name: {{ category.name }}</h1>
       <div class="row">
          {% for item in category.category_item.all %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ item.get_absolute_url }}"><img class="card-img-top" src="{{ item.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                </h4>
                <h5>
                  <strong>€
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h5>
                <p class="card-text"><a href="{% url 'shop:category' item.category.slug %}">{{ item.category.name }}</a></p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
    {% endblock content %}

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block aside_menu %}{% endblock aside_menu %}

{% block content %}
  <main>
    <div class="container wow fadeIn">
      <h2 class="my-5 h2">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            {% comment %}
            <form>
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary" type="submit">Checkout</button>
            </form>
            {% endcomment %}
            <form class="card-body" method="post">
              {% csrf_token %}
              <div class="md-form mb-5">
                {% comment %}<input type="text" id="address" class="form-control" placeholder="">{% endcomment %}
                {{ form.street_addres }}
                <label for="address" class="">Address</label>
              </div>
              <div class="md-form mb-5">
                {% comment %}<input type="text" id="address-2" class="form-control" placeholder="">{% endcomment %}
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>
              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {% comment %}
                  <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select>
                  {% endcomment %}
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="zip">Zip</label>
                  {% comment %}<input type="text" class="form-control" id="zip" placeholder="" required>{% endcomment %}
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>
              <hr>
              <div class="custom-control custom-checkbox">
                <input {% if form.same_shipping_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name='same_shipping_address' id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name='save_info' id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>
              <hr>
              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                  <div class="custom-control custom-radio">
                    <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                    <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                  </div>
                {% endfor %}
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
  <!-- Page Content -->
    {% block content %}
        <div class="mt-5 mb-5">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-primary" role="alert">
                        {{ message }}
                    </div>
                {% endfor  %}
            {% endif %}
        </div>
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
              {% if headers %}
                  {% for image in headers %}
                    <div class="carousel-item {% if image == headers.0 %}active {% endif %}">
                      <img class="d-block img-fluid" src="{{ image.image.url }}" alt="" style="width:900px; height:350px">
                    </div>
                  {% endfor %}
              {% else %}
                    <div class="carousel-item">
                      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Example slide">
                    </div>
              {% endif %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
        {% if object_list %}
              {% for item in object_list %}
              <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                  <a href="{{ item.get_absolute_url }}"><img class="card-img-top" src="{{ item.image.url }}" alt=""></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                    </h4>
                    <h5>
                      <strong>€
                      {% if item.discount_price %}
                      {{ item.discount_price }}
                      {% else %}
                      {{ item.price }}
                      {% endif %}
                      </strong>
                    </h5>
                    <p class="card-text">{% if item.category %}<a href="{% url 'shop:category' item.category.slug %}">{{ item.category.name }}</a>{% endif %}</p>
                  </div>
                </div>
              </div>
              {% endfor %}
          {% else %}
            <h2>No product items</h2>
          {% endif %}
        </div>

        {% if is_paginated %}
            <nav aria-label="..." class="mt-3">
              <ul class="justify-content-center pagination pagination-sm">
                  {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <span class="page-link">Previous</span>
                    </li>
                  {% endif %}

                  {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="page-item active" aria-current="page"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                      {% endif %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Next</span>
                    </li>
                  {% endif %}
              </ul>
            </nav>
        {% endif %}
    {% endblock content %}

templates/order_summary.html
{% extends "base.html" %}

{% block aside_menu %}{% endblock aside_menu %}

{% block content %}
  <main>
    <div class="container">
        <div class="table-responsive text-nowrap my-4">
          <h2>Order summary</h2>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total item price</th>
              </tr>
            </thead>
            <tbody>
            {% for order_item in object.items.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order_item.item.title }}</td>
                <td>{{ order_item.item.price }}</td>
                <td>
                  <a href="{% url 'shop:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                  {{ order_item.quantity }}
                  <a href="{% url 'shop:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                </td>
                <td>
                  {% if order_item.item.discount_price%}
                    €{{ order_item.get_total_discount_item_price }}
                    <span class="badge badge-primary">Saving: €{{ order_item.get_amount_saved }}</span>
                  {% else %}
                    ${{ order_item.get_total_item_price }}
                  {% endif %}
                  <a style="color:red;" href="{% url 'shop:remove-from-cart' order_item.item.slug %}">
                    <i class="fas fa-trash float-right"></i>
                  </a>
                </td>
              </tr>
            {% empty %}
            <tr>
              <td colspan="5">Your card is empty</td>
              <tr>
                <td colspan="5">
                  <a class="btn btn-primary float-right" href="/">Continue shoping</a>
                </td>
              </tr>
            </tr>
            {% endfor %}
            {% if object.get_total %}
              <tr>
                <td colspan="4">Order total:</td>
                <td>€{{ object.get_total }}</td>
              </tr>
              <tr>
                <td colspan="5">
                  <a class="btn btn-warning float-right ml-2" href="{% url 'shop:checkout' %}">Procced to checkout</a>
                  <a class="btn btn-primary float-right" href="/">Continue shoping</a>
                </td>
              </tr>
            {% endif %}
            </tbody>
          </table>
        </div>
    </div>
  </main>

{% endblock content %}

templates/payment.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'js/client.js' %}" defer></script>
{% endblock extra_head %}

{% block aside_menu %}{% endblock aside_menu %}

{% block content %}
  <div class="row justify-content-md-center mb-5 mt-5">
    <form action="." method="post" id="payment-form">
      {% csrf_token %}
      <input type="hidden" name="use_default" value="true">
      <div id="card-element"><!--Stripe.js injects the Card Element--></div>
      <div class="stripe-form-row">
        <button id="stripeBtn">Submit Payment</button>
      </div>
      <div id="card-errors" role="alert"></div>
    </form>
  </div>

  <div class="mb-5 mt-5">
    <ul class="list-group">
        {% for order_item in order.items.all %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ order_item.quantity }} x {{ order_item.item.title }}
        <span class="badge badge-primary badge-pill">{{ order_item.get_final_price }}</span>
      </li>
        {% endfor %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
          <span><strong>Total (Euro)</strong></span>
          <span class="badge badge-primary badge-pill">€{{ order.get_total }}</span>
      </li>
    </ul>
  </div>
{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <div class="card mt-4 my-4">
          <img class="card-img-top img-fluid" src="{{ object.image.url }}" alt="">
          <div class="card-body">
            <h3 class="card-title">{{ object.title }} {% if object.category %} | <a href="{% url 'shop:category' object.category.slug %}">{{ object.category.name }}</a> {% endif %} </h3>
            <h4>
                <span class="mr-1">
                {% if object.discount_price %}
                  <del>{{ object.price }}</del>
                {% endif %}
              </span>
              <span>€
                {% if object.discount_price %}
                  {{ object.discount_price }}
                {% else %}
                  {{ object.price }}
                {% endif %}
              </span>
            </h4>
            <p class="card-text">{{ object.description|linebreaks }}</p>
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from cart</a>
          </div>
        </div>
        <!-- /.card -->
{% endblock content %}

templates/user_summary.html
{% extends 'base.html' %}
{% load static %}
{% block aside_menu %}{% endblock aside_menu %}
    {% block content %}
        <h2 class="mt-5 mb-5">Order summary for: {{ user.username }}</h2>
        <div class="row justify-content-md-center mb-5 mt-5">
            <h2>Items already ordered</h2>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Price</th>
                </tr>
              </thead>
              <tbody>
                    {% for order in done %}
                        <tr>
                            <td>{{ order.start_date }}</td>
                            <td>{{ order.payment.amount }}</td>
                        </tr>
                    {% endfor %}
              </tbody>
            </table>

            <h2>Items in progress</h2>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Price</th></tr>
              </thead>
              <tbody>
              <tbody>
                    {% for order in in_progress %}
                        <tr>
                            <td>{{ order.start_date }}</td>
                            <td>{{ order.payment.amount }}</td>
                        </tr>
                    {% endfor %}
              </tbody>
              </tbody>
            </table>

        </div>
    {% endblock content %}